package com.zulfakarelzaf.authenticjogja.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zulfakarelzaf.authenticjogja.database.Saved;

import com.zulfakarelzaf.authenticjogja.database.SavedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig savedDaoConfig;

    private final SavedDao savedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        savedDaoConfig = daoConfigMap.get(SavedDao.class).clone();
        savedDaoConfig.initIdentityScope(type);

        savedDao = new SavedDao(savedDaoConfig, this);

        registerDao(Saved.class, savedDao);
    }
    
    public void clear() {
        savedDaoConfig.clearIdentityScope();
    }

    public SavedDao getSavedDao() {
        return savedDao;
    }

}
