package com.zulfakarelzaf.authenticjogja.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SAVED".
 */
@Entity
public class Saved {

    @Id(autoincrement = true)
    private Long id;
    private int item_id;
    private int jenis;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Saved() {
    }

    public Saved(Long id) {
        this.id = id;
    }

    @Generated
    public Saved(Long id, int item_id, int jenis) {
        this.id = id;
        this.item_id = item_id;
        this.jenis = jenis;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getItem_id() {
        return item_id;
    }

    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }

    public int getJenis() {
        return jenis;
    }

    public void setJenis(int jenis) {
        this.jenis = jenis;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
